version: "3.0"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    expose:
      - "5432"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"